package br.ufma.ecp;

public enum TokenType {
  PLUS, MINUS, ASSIGN, ASTERISK, SLASH, AND, OR, NOT, DOT, LT, GT, COMMA, 
  SEMICOLON, LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,

  NUMBER,

  STRING,

  IDENTIFIER,

  //keywords
  WHILE, CLASS, CONSTRUCTOR, FUNCTION, METHOD, FIELD, STATIC, VAR, INT, CHAR,
  BOOLEAN, VOID, TRUE, FALSE, NULL, THIS, LET, DO, IF, ELSE, RETURN,

  EOF,

  ILLEGAL
}
