package br.ufma.ecp;

public enum TokenType {
  PLUS, MINUS,

  NUMBER,

  IDENTIFIER,

  //keywords
  WHILE, CLASS, CONSTRUCTOR, FUNCTION, METHOD, FIELD, STATIC, VAR, INT, CHAR,
  BOOLEAN, VOID, TRUE, FALSE, NULL, THIS, LET, DO, IF, ELSE, RETURN,

  EOF,

  ILLEGAL
}
